#GPU ID
gpu: 0
world_size: 1
# The name of this exp
name: 'MSCSWT-Net'
ckpt_path: './ckpt/'

# The config file of each experiment
config_path: './config_list/'

# start from where, the default is latest
resume_ckpt: None #'C:/MSCSWT-Net/ckpt/xxx/model_last.pth'
resume_D_ckpt: None #'C:/MSCSWT-Net/ckpt/xxx/Discriminator_last.pth'
test_ckpt: None #'C:/MSCSWT-Net/ckpt/xxx/model_bestPSNR.pth'

# data_path & mask_path should be .txt
data_path: 'C:/MSCSWT-Net/txt/xxx.txt'
mask_path: 'C:/MSCSWT-Net/txt/xxx_mask.txt'

# Train
batch_size: 8  # If changed > HSV loss need change too
train_epoch: 100
weight_decay : 0.1
learning_rate: 0.001
lr_decay : True
lr_min: 1e-6
warmup_epoch : 5
D_learning_rate: 0.001
D_lr_decay : True
D_lr_min: 1e-6
D_warmup_epoch : 5
grad_norm_clip: 1.0
# Loss
Lambda_LD1  : 10  #real
Lambda_LD2  : 10  #fake
Lambda_L1: 10
Lambda_Perceptual: 0.1
Lambda_LG  : 10
Lambda_Style: 250
Lambda_LHSV: 1

# Define the size of transformer
n_embd: [256, 256, 256, 256]
n_head: 8   #8>4
embd_pdrop: 0.0
resid_pdrop: 0.0
attn_pdrop: 0.0
block_size: 32
# Define the Gated Conv
activation: 'lrelu'
norm: 'bn'
# cswin transformer
split_size: [4, 8, 16, 32] # [4, 8, 16, 32]
head: [4, 4, 8, 16]  # [2, 4, 8, 16]
dim: [256, 256, 256, 256]
loop_time: [4, 2, 2, 1] # 1 2 21 1  [8, 4, 2, 1]

# where is the validation set of ImageNet
val_path: 'C:/MSCSWT-Net/txt/xxx.txt'
val_mask_path: 'C:/MSCSWT-Net/txt/xxx_mask.txt'
test_path: 'C:/MSCSWT-Net/txt/xxx.txt'
test_mask_1~60_path: 'C:/MSCSWT-Net/txt/xxx_mask.txt'
save_img_path: 'C:/MSCSWT-Net/out/MSCSWT-Net_out/'
image_size: 256

